launch: #起動パラメータ
  ros__parameters:
    real: false

/**:  #ワイルドカード(ここのパラメータは全ノードから読める)
  ros__parameters:
    # 並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max_vel: 0.0
    linear_max_acc: 0.0
    linear_max_dec: 0.0
    linear_max_jer: 0.0
    # 回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2],躍度[deg/s^3]
    angular_max_vel: 0.0
    angular_max_acc: 0.0
    angular_max_dec: 0.0
    angular_max_jer: 0.0

mcl_2d_node:
  ros__parameters:
    num_of_particle: 50     #粒子数
    odom_convariance:
      param1: 0.0   #回転成分から生まれる回転成分のズレ
      param2: 0.0   #並進成分から生まれる回転成分のズレ
      param3: 0.0   #並進成分から生まれる並進成分のズレ
      param4: 0.0   #回転成分から生まれる並進成分のズレ
      param5: 0.01   #Xのズレ
      param6: 0.01   #Yのズレ
    initial_pose: [-5.45, 0.0, 0.0]  #初期位置[x,y,yaw]
    tf_laser2robot: [0.4655,0.0,0.0,  3.14159,0.0,0.0]  #ロボット->lidarのTF[x,y,z,r,p,y]
