launch: #起動パラメータ
  ros__parameters:
    slcan: false
    scan: false
    tcp_endpoint: false
    trajectory_planner: true
    

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    initial_pose: [0.35, 0.5, 0.0]  #初期位置[x,y,yaw]
    2nd_initial_pose: [5.5, 0.35, 0.0]  #2つ目の初期位置[x,y,yaw]
    tf_laser2robot: [0.3,0.0,0.0,  3.14159,0.0,0.0]  #ロボット->lidarのTF[x,y,z,r,p,y]
    court_color: "red" #コート情報

    # 自動の並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max_vel: 3.0
    linear_max_acc: 4.0
    linear_max_dec: 4.0
    linear_max_jer: 0.0
    # 回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2],躍度[deg/s^3]
    angular_max_vel: 270.0
    angular_max_acc: 230.0
    angular_max_dec: 230.0
    angular_max_jer: 0.0

    canid:
      emergency: 0x000
      heartbeat: 0x001
      restart: 0x002
      linear: 0x100
      angular: 0x101
      movable: 0x130
      inject: 0x200
      injectable: 0x201
      cancel_inject: 0x202
      calculatable: 0x203
      main_digital_button: 0x220
      sub_digital_button: 0x221
      odom_linear: 0x110
      odom_angular: 0x111
      init_angular: 0x120
      
    port:
      joy_main: 50000
      pole_share: 53000
      spline_state: 55000
      robot_state: 57000
      
    ip:
      r1_pc: "192.168.1.2"
      r2_pc: "192.168.1.3"

controller_interface_node:
  ros__parameters:
    # 手動の高速　並進　速度[m/s],加速度[m/s^2],加減速度[-m/s^2]
    high_linear_max_vel: 1.0
    high_linear_max_acc: 2.0
    high_linear_max_dec: 2.0
    # 手動の低速　並進　速度[m/s],加速度[m/s^2],加減速度[-m/s^2]
    slow_linear_max_vel: 0.5
    slow_linear_max_acc: 1.0
    slow_linear_max_dec: 1.0
    # 手動の回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2]
    angular_max_vel: 45.0
    angular_max_acc: 180.0
    angular_max_dec: 180.0
    
    heartbeat_ms: 100 #ハートビート周期[ms]
    convergence_ms: 100 #収束周期[ms]

    interval_ms: 50
    start_ms: 3000
    
    #リスタート、緊急、足回りの手自動、上物の手自動、手動の射角、ボタンのカラー情報
    defalt_restart_flag: false
    defalt_emergency_flag: true
    defalt_move_autonomous_flag: true
    defalt_injection_autonomous_flag: true
    defalt_slow_speed_flag: true
    defalt_color_information_flag: true

    #収束の初期値
    defalt_spline_convergence: false
    defalt_injection_calculator_convergence: false
    defalt_injection_convergence: false
    defalt_seedlinghand_convergence: false
    defalt_ballhand0_convergence: false
    defalt_ballhand1_convergence: false

    initial_pickup_state: "A"
    initial_inject_state: "B"

injection_interface_node:
  ros__parameters:
    tf_injection2robot: [0.0, 0.0] #射出機構のTF[x, y]
    strage_backside: [0.0, 0.0, 0.0] #ストレージエリアの[x, y, 高さ]
    strage_front: [0.1, 0.0, 0.0]

rasnac_localization:
  ros__parameters:
    plot_mode: true #実機のときはfalse
    laser_weight: 1.0 #lidarの重み->値を大きくするとlidarが優先される
    odom_weight_liner: 1.0e-5 #値が大きくなると共分散が小さくなる
    odom_weight_angler: 1.0e-5
    voxel_size: 0.05
    trial_num: 40
    inlier_dist_threshold: 0.01
    inlier_length_threshold: 1.0 #インライアのしきい値
    