/**:
    ros__parameters:
      ndt_resolution: 0.005
      ndt_step_size: 0.01
      transform_epsilon: 0.1
      voxel_leaf_size: 0.005
      scan_period: 0.1
      use_pcd_map: true
      set_initial_pose: true
      initial_pose_x: 0.55
      initial_pose_y: 6.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 1.0
      use_odom: false
      use_imu: false
      enable_debug: false
