icp_base_slam:
  ros__parameters:
    plot_mode: true
    use_gazebo_simulator: true
    registration_method: "NDT2D"
    voxel_leaf_size: 1.0
    laser_weight: 1.0 # 退化で極端にずれる場合は=1,通常=0.1
    odom_weight: 1.0 # オドメトリのずれが大きい場合=100,通常=10

    #ndt
    transformation_epsilon: 0.05
    ndt_resolution: 1.7
    ndt_step_size: 0.1

    # ndt2d
    maximum_iterations: 1
    grid_centre_x: -6.0
    grid_centre_y: -6.0
    grid_extent_x: 7.0
    grid_extent_y: 13.0
    grid_step: 1.7
    optimization_step_size: 0.3
    transformation_epsilon_2d: 0.1
    map_voxel_leaf_size: 0.3
